In [1]:
!python -m pip install konlpy

In [2]:
# from preprocess import *
import preprocess as pp

In [3]:
path_csv = './ChatBotData.csv_short'
inputs, outputs = pp.load_data(path_csv)
type(inputs), type(outputs)

(list, list)

In [4]:
inputs[7], outputs[7]

('가스불 켜놓고 나온거 같아', '빨리 집에 돌아가서 끄고 나오세요.')

In [5]:
inputs[10], outputs[10], len(inputs), len(outputs)

('남자친구 교회 데려가고 싶어', '마음을 열 때까지 설득해보세요.', 20, 20)

In [6]:
path_vocab = './vocabulary.txt'
char2idx, idx2char, vocab_size = pp.load_vocabulary(path_csv, path_vocab)
type(char2idx), type(idx2char), type(vocab_size)

(dict, dict, int)

In [7]:
print(char2idx)

{'<PAD>': 0, '<SOS>': 1, '<END>': 2, '<UNK>': 3, '운동': 4, '가상화폐': 5, '나온거': 6, '있어도': 7, '적당히': 8, '오늘': 9, '것': 10, '좋을': 11, '돈은': 12, '운동만': 13, '걸리겠어': 14, '훈훈해': 15, '달에는': 16, '빨리': 17, '전생에': 18, '데려가고': 19, '가난한': 20, '혼자를': 21, '생일인데': 22, '너무': 23, '쫄딱': 24, '때까지': 25, '같아': 26, '뭐가': 27, '생각해보세요': 28, '켜놓고': 29, '자의': 30, '좀': 31, '거예요': 32, '잘생겼어': 33, '운동을': 34, '좋다': 35, '구하셨나요': 36, '그': 37, '사세요': 38, '빠를수록': 39, '선물로': 40, '가끔': 41, '필요했던': 42, '같아요': 43, '사람도': 44, '갔어': 45, '평소에': 46, '마세요': 47, '식혀주세요': 48, '새출발': 49, '해보세요': 50, '즐기세요': 51, '따라': 52, '끄고': 53, '좋을까': 54, '승진': 55, '결단은': 56, '어서': 57, '들어올': 58, '나갔어': 59, '바빠': 60, '열': 61, '망함': 62, '궁금해': 63, '거짓말': 64, '남자친구가': 65, '땀을': 66, '가스불': 67, '돌아가서': 68, '게': 69, '남자친구': 70, '비싼데': 71, '나오세요': 72, '따뜻하게': 73, '나': 74, '좋아요': 75, '많이': 76, '가스비': 77, '집착하지': 78, '땀난다': 79, '뭐하는지': 80, '다시': 81, '더': 82, '해': 83, '보인다': 84, '하세요': 85, '나라를': 86, '필요한': 87, '마음을': 88, '나왔다': 89, '잊고': 90, '안': 91, '믿어줘':

In [8]:
print(idx2char)

{0: '<PAD>', 1: '<SOS>', 2: '<END>', 3: '<UNK>', 4: '운동', 5: '가상화폐', 6: '나온거', 7: '있어도', 8: '적당히', 9: '오늘', 10: '것', 11: '좋을', 12: '돈은', 13: '운동만', 14: '걸리겠어', 15: '훈훈해', 16: '달에는', 17: '빨리', 18: '전생에', 19: '데려가고', 20: '가난한', 21: '혼자를', 22: '생일인데', 23: '너무', 24: '쫄딱', 25: '때까지', 26: '같아', 27: '뭐가', 28: '생각해보세요', 29: '켜놓고', 30: '자의', 31: '좀', 32: '거예요', 33: '잘생겼어', 34: '운동을', 35: '좋다', 36: '구하셨나요', 37: '그', 38: '사세요', 39: '빠를수록', 40: '선물로', 41: '가끔', 42: '필요했던', 43: '같아요', 44: '사람도', 45: '갔어', 46: '평소에', 47: '마세요', 48: '식혀주세요', 49: '새출발', 50: '해보세요', 51: '즐기세요', 52: '따라', 53: '끄고', 54: '좋을까', 55: '승진', 56: '결단은', 57: '어서', 58: '들어올', 59: '나갔어', 60: '바빠', 61: '열', 62: '망함', 63: '궁금해', 64: '거짓말', 65: '남자친구가', 66: '땀을', 67: '가스불', 68: '돌아가서', 69: '게', 70: '남자친구', 71: '비싼데', 72: '나오세요', 73: '따뜻하게', 74: '나', 75: '좋아요', 76: '많이', 77: '가스비', 78: '집착하지', 79: '땀난다', 80: '뭐하는지', 81: '다시', 82: '더', 83: '해', 84: '보인다', 85: '하세요', 86: '나라를', 87: '필요한', 88: '마음을', 89: '나왔다', 90: '잊고', 91: '안', 92: '믿

In [9]:
print(vocab_size)

111


In [12]:
idx_inputs, inputs_seq_len = pp.enc_processing(inputs, char2idx)
type(idx_inputs), len(inputs_seq_len), inputs_seq_len

(numpy.ndarray,
 20,
 [2, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 5, 5, 4, 4, 3, 4, 3])

In [13]:
idx_inputs[3:5]   # 0으로 채워져 있는 것으로 보아 패딩 시퀀스까지 다 되었음을 볼 수 있다. 

array([[ 20,  30, 107,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [ 93,   7,  79,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0]])

In [14]:
idx_outputs, outputs_seq_len = pp.dec_output_processing(outputs, char2idx)
type(idx_outputs), len(outputs_seq_len)

(numpy.ndarray, 20)

In [15]:
idx_outputs[3:5]

array([[ 1, 12, 81, 58, 32,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 1, 66, 48,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0]])

In [16]:
idx_targets = pp.dec_target_processing(outputs, char2idx)
type(idx_targets), len(idx_targets)

(numpy.ndarray, 20)

In [17]:
idx_targets[3:5]

array([[12, 81, 58, 32,  2,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0],
       [66, 48,  2,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0]])

### 넘파이로 저장하여 사용한다. (숫자만 들어간 데이터일 경우 넘파이가 좋다)

In [20]:
import numpy as np

In [21]:
np.save(open('./train_inputs.npy', 'wb'), idx_inputs)

In [24]:
np.save(open('./train_outputs.npy', 'wb'), idx_outputs)

In [25]:
np.save(open('./train_targets.npy', 'wb'), idx_targets)

In [18]:
data_configs = dict()

In [27]:
data_configs['char2idx'] = char2idx
data_configs['idx2char'] = idx2char
data_configs['vocab_size'] = vocab_size

data_configs['pad_symbol'] = '<PAD>'
data_configs['std_symbol'] = '<STD>'
data_configs['end_symbol'] = '<END>'
data_configs['unk_symbol'] = '<UNK>'

In [28]:
pp.json.dump(data_configs, open('./data_configs.json', 'w'))