# sigmoid

In [4]:
import tensorflow as tf

In [11]:
a = tf.constant([4.0, 1.0, 3.0], dtype = tf.float32)     # 행렬이 벡터다. 
a, type(a)

(<tf.Tensor: shape=(3,), dtype=float32, numpy=array([4., 1., 3.], dtype=float32)>,
 tensorflow.python.framework.ops.EagerTensor)

In [12]:
b = tf.keras.activations.sigmoid(a)
b

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.98201376, 0.7310586 , 0.95257413], dtype=float32)>

In [13]:
b.numpy()

array([0.98201376, 0.7310586 , 0.95257413], dtype=float32)

# softmax

In [21]:
inputs = tf.random.normal(shape=(1, 3))
inputs

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[-0.85974294, -1.564476  ,  0.31319636]], dtype=float32)>

In [22]:
outputs = tf.keras.activations.softmax(inputs)
outputs

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0.21160808, 0.10458528, 0.68380666]], dtype=float32)>

In [23]:
outputs.numpy()

array([[0.21160808, 0.10458528, 0.68380666]], dtype=float32)

소프트맥스는 0과 1사이의 값으로 수렴하고 합산을 하면 1이 된다. 그래서 output의 unique값이 3개 이상일 경우 softmax를 쓴다. 