In [1]:
from sklearn import datasets

In [ ]:
iris = datasets.load_iris()
iris, type(iris)

In [3]:
import pandas as pd

In [39]:
df_iris = pd.DataFrame(iris['data'])
df_iris.info(), type(df_iris)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       150 non-null    float64
 1   1       150 non-null    float64
 2   2       150 non-null    float64
 3   3       150 non-null    float64
dtypes: float64(4)
memory usage: 4.8 KB


(None, pandas.core.frame.DataFrame)

# DB에 넣기

In [7]:
import sqlite3

In [8]:
connect = sqlite3.connect('./db.sqlite3')

In [10]:
df_iris.to_sql('iris_resource', connect, if_exists='append', index=False)

In [11]:
df_load = pd.read_sql_query('select * from iris_resource', connect)
df_load.head(4)

0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2

In [12]:
# 이제 판다스에서 넘파이만 빼내야 한다. (판다스에서 index와 columns를 빼고 데이터만 가져온다)

In [14]:
x_data = df_load.to_numpy()
x_data.shape                     # 컬럼이 4개라는 것을 알 수 있다. 

(150, 4)

In [20]:
import numpy as np

In [21]:
y_data = iris.target
y_data, np.unique(y_data)

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]),
 array([0, 1, 2]))

# 교육단계

In [41]:
import tensorflow as tf

In [42]:
model = tf.keras.Sequential()

In [43]:
model.add(tf.keras.Input(shape=4,))  # input layer

model.add(tf.keras.layers.Dense(64, activation='relu'))  # hidden layer
model.add(tf.keras.layers.Dense(24, activation='relu'))  # hidden layer

model.add(tf.keras.layers.Dense(3, activation='softmax'))  # output layer

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['acc']) # gadget    연속형일 때 mae


In [44]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_6 (Dense)              (None, 64)                320       
_________________________________________________________________
dense_7 (Dense)              (None, 24)                1560      
_________________________________________________________________
dense_8 (Dense)              (None, 3)                 75        
Total params: 1,955
Trainable params: 1,955
Non-trainable params: 0
_________________________________________________________________


In [45]:
 model.fit(x_data, y_data, epochs=50, validation_split=0.3)  # 학습   한쪽으로 쏠리는 것을 방지하기 위해 validation_split을 쓴다. 

Epoch 1/50
4/4 [==============================] - 0s 49ms/step - loss: 1.6261 - acc: 0.4762 - val_loss: 1.9844 - val_acc: 0.0000e+00
Epoch 2/50
4/4 [==============================] - 0s 8ms/step - loss: 1.3238 - acc: 0.4762 - val_loss: 1.8477 - val_acc: 0.0000e+00
Epoch 3/50
4/4 [==============================] - 0s 7ms/step - loss: 1.0919 - acc: 0.4762 - val_loss: 1.6926 - val_acc: 0.0000e+00
Epoch 4/50
4/4 [==============================] - 0s 8ms/step - loss: 0.9135 - acc: 0.4762 - val_loss: 1.6924 - val_acc: 0.0000e+00
Epoch 5/50
4/4 [==============================] - 0s 8ms/step - loss: 0.7740 - acc: 0.7524 - val_loss: 1.8663 - val_acc: 0.0000e+00
Epoch 6/50
4/4 [==============================] - 0s 8ms/step - loss: 0.6647 - acc: 0.9524 - val_loss: 2.1256 - val_acc: 0.0000e+00
Epoch 7/50
4/4 [==============================] - 0s 8ms/step - loss: 0.5833 - acc: 0.9524 - val_loss: 2.3976 - val_acc: 0.0000e+00
Epoch 8/50
4/4 [==============================] - 0s 8ms/step - loss: 0.525

# evaluation

In [46]:
model.evaluate(x_data, y_data)

5/5 [==============================] - 0s 2ms/step - loss: 0.6223 - acc: 0.6667


[0.6222662925720215, 0.6666666865348816]

# service

In [47]:
x_data[25], y_data[25]

(array([5. , 3. , 1.6, 0.2]), 0)

In [48]:
pred = model.predict([[5. , 3. , 1.6, 0.2]])
pred

array([[0.9718085 , 0.02652619, 0.00166535]], dtype=float32)

In [49]:
import numpy as np

In [50]:
np.argmax(pred)

0