<a href="https://colab.research.google.com/github/victoria2012/test_deeplearning/blob/master/Notescale_LSTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [86]:
note_seq = ['g8', 'e8', 'e4', 'f8', 'd8', 'd4', 'c8', 'd8', 'e8', 'f8', 'g8', 'g8', 'g4',
       'g8', 'e8', 'e8', 'e8', 'f8', 'd8', 'd4', 'c8', 'e8', 'g8', 'g8', 'e8', 'e8', 'e4',
       'd8', 'd8', 'd8', 'd8', 'd8', 'e8', 'f4', 'e8', 'e8', 'e8', 'e8', 'e8', 'f8', 'g4',
       'g8', 'e8', 'e4', 'f8', 'd8', 'd4', 'c8', 'e8', 'g8', 'g8', 'e8', 'e8', 'e4']

In [87]:
note_seq[0:4], note_seq[1:5], note_seq[2:6]

(['g8', 'e8', 'e4', 'f8'], ['e8', 'e4', 'f8', 'd8'], ['e4', 'f8', 'd8', 'd4'])

In [88]:
code2idx = {'c4':0, 'd4':1, 'e4':2, 'f4':3, 'g4':4, 'a4':5, 'b4':6,
            'c8':7, 'd8':8, 'e8':9, 'f8':10, 'g8':11, 'a8':12, 'b8':13}


In [89]:
len(note_seq), range(len(note_seq)-4) # [4,8,12.....]

(54, range(0, 50))

In [90]:
code2idx['c4']

0

In [91]:
dataset = list()
for i in range(len(note_seq)-4):
  subset = note_seq[i:i+4]
  items = list()
  # print(subset)
  for item in subset:
    code2idx[item]
    # print(code2idx[item])
    items.append(code2idx[item])
  # print(items)
  dataset.append(items)
print(dataset)

[[11, 9, 2, 10], [9, 2, 10, 8], [2, 10, 8, 1], [10, 8, 1, 7], [8, 1, 7, 8], [1, 7, 8, 9], [7, 8, 9, 10], [8, 9, 10, 11], [9, 10, 11, 11], [10, 11, 11, 4], [11, 11, 4, 11], [11, 4, 11, 9], [4, 11, 9, 9], [11, 9, 9, 9], [9, 9, 9, 10], [9, 9, 10, 8], [9, 10, 8, 1], [10, 8, 1, 7], [8, 1, 7, 9], [1, 7, 9, 11], [7, 9, 11, 11], [9, 11, 11, 9], [11, 11, 9, 9], [11, 9, 9, 2], [9, 9, 2, 8], [9, 2, 8, 8], [2, 8, 8, 8], [8, 8, 8, 8], [8, 8, 8, 8], [8, 8, 8, 9], [8, 8, 9, 3], [8, 9, 3, 9], [9, 3, 9, 9], [3, 9, 9, 9], [9, 9, 9, 9], [9, 9, 9, 9], [9, 9, 9, 10], [9, 9, 10, 4], [9, 10, 4, 11], [10, 4, 11, 9], [4, 11, 9, 2], [11, 9, 2, 10], [9, 2, 10, 8], [2, 10, 8, 1], [10, 8, 1, 7], [8, 1, 7, 9], [1, 7, 9, 11], [7, 9, 11, 11], [9, 11, 11, 9], [11, 11, 9, 9]]


In [92]:
import numpy as np
datasets = np.array(dataset)

In [93]:
x_train = datasets[:,0:3]
x_train.shape, x_train

((50, 3), array([[11,  9,  2],
        [ 9,  2, 10],
        [ 2, 10,  8],
        [10,  8,  1],
        [ 8,  1,  7],
        [ 1,  7,  8],
        [ 7,  8,  9],
        [ 8,  9, 10],
        [ 9, 10, 11],
        [10, 11, 11],
        [11, 11,  4],
        [11,  4, 11],
        [ 4, 11,  9],
        [11,  9,  9],
        [ 9,  9,  9],
        [ 9,  9, 10],
        [ 9, 10,  8],
        [10,  8,  1],
        [ 8,  1,  7],
        [ 1,  7,  9],
        [ 7,  9, 11],
        [ 9, 11, 11],
        [11, 11,  9],
        [11,  9,  9],
        [ 9,  9,  2],
        [ 9,  2,  8],
        [ 2,  8,  8],
        [ 8,  8,  8],
        [ 8,  8,  8],
        [ 8,  8,  8],
        [ 8,  8,  9],
        [ 8,  9,  3],
        [ 9,  3,  9],
        [ 3,  9,  9],
        [ 9,  9,  9],
        [ 9,  9,  9],
        [ 9,  9,  9],
        [ 9,  9, 10],
        [ 9, 10,  4],
        [10,  4, 11],
        [ 4, 11,  9],
        [11,  9,  2],
        [ 9,  2, 10],
        [ 2, 10,  8],
        [10,  8,  1],
 

In [94]:
y_train = datasets[:,3]
y_train.shape, y_train

((50,),
 array([10,  8,  1,  7,  8,  9, 10, 11, 11,  4, 11,  9,  9,  9, 10,  8,  1,
         7,  9, 11, 11,  9,  9,  2,  8,  8,  8,  8,  8,  9,  3,  9,  9,  9,
         9,  9, 10,  4, 11,  9,  2, 10,  8,  1,  7,  9, 11, 11,  9,  9]))

In [95]:
len(code2idx)

14

In [96]:
x_train = x_train / 13    # 정규화 min max 스케일링
x_train[3]

array([0.76923077, 0.61538462, 0.07692308])

In [97]:
# make model

In [98]:
import tensorflow as tf

In [99]:
x_train.shape, x_train[2]   # 현재는 넘파이, 스칼라 --> tensorflow type(tensor) 그러면 (50, 3, 1)로 바뀐다. 

((50, 3), array([0.15384615, 0.76923077, 0.61538462]))

In [100]:
X_train = np.reshape(x_train, (50, 3, 1))   # reshape된 tensor의 모양, 위치값이 명확하다. 
X_train.shape, X_train[2]

((50, 3, 1), array([[0.15384615],
        [0.76923077],
        [0.61538462]]))

In [101]:
np.unique(y_train)     # unique는 9개지만 code2idx를 봤을 때 13개의 의견이 나와야 하므로 output에 13개

array([ 1,  2,  3,  4,  7,  8,  9, 10, 11])

In [102]:
model = tf.keras.models.Sequential()

In [103]:
model.add(tf.keras.Input(shape=(3, 1))) # input layer    임베딩할 필요가 없다. 그 값을 그대로 사용하기 때문에
model.add(tf.keras.layers.LSTM(128)) # input and hideen layer  # tensor의 모양으로 바꿔줘야 한다. (batch_size, tiemsteps, input_dim) --> (rows, cols, 1)   input_dim 한번에 처리할 수 있는 행의 갯수
model.add(tf.keras.layers.Dense(13, activation='softmax')) # output layer

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['acc'])  # gadget

In [107]:
hist = model.fit(X_train, y_train, epochs=2, batch_size=10)

Epoch 1/2
5/5 [==============================] - 1s 6ms/step - loss: 1.9383 - acc: 0.3400
Epoch 2/2
5/5 [==============================] - 0s 5ms/step - loss: 1.9316 - acc: 0.3400


# evaluation

In [108]:
model.evaluate(X_train, y_train)

2/2 [==============================] - 0s 8ms/step - loss: 1.9268 - acc: 0.3400


[1.926841139793396, 0.3400000035762787]

In [109]:
model.predict(X_train[4:5])

array([[0.01617569, 0.06399161, 0.05124573, 0.03313773, 0.05414357,
        0.01464881, 0.01514724, 0.06504932, 0.15325011, 0.28126413,
        0.09270718, 0.14447176, 0.0147671 ]], dtype=float32)